### ISSUE TITLE
报错,希望修复一下webView的这个错误(应该是webView的错误吧)

### ISSUE THREAD

**Issue by Para123123** [youlookwhat/WebViewStudy#19]
` java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at com.android.webview.chromium.WebViewContentsClientAdapter.getDefaultVideoPoster(WebViewContentsClientAdapter.java:1142)
        at org.chromium.android_webview.DefaultVideoPosterRequestHandler$1.run(DefaultVideoPosterRequestHandler.java:39)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:5958)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)`

**Comment by youlookwhat** [comment]
好的，这个是系统的一个错误，我马上修复一下

**Comment by youlookwhat** [comment]
可以啦，引用最新的包即可~ 
`implementation 'com.github.youlookwhat:ByWebView:1.1.1'`

**Comment by Para123123** [comment]
谢谢
